# Build react client
FROM node:latest

# Working directory be app
WORKDIR /src

COPY ["package.json", "package-lock.json*", "./"]

###  Installing dependencies

RUN npm install --silent

# copy local files to app folder
COPY . .

EXPOSE 3000

CMD ["npm","start"]

